name: Cleanup Old Releases

on:
  workflow_run:
    workflows: ["Build and Release"]
    types: [completed]

jobs:
  delete-old-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: Nats-ji/delete-old-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 1
          remove-tags: false
